# Generated by Django 4.0.6 on 2022-08-25 06:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='adminUserModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefonNumarasi', models.CharField(max_length=15)),
                ('guncellenmeTarihi', models.DateTimeField(auto_now=True)),
                ('hesap_olusturma_tarihi', models.DateTimeField(auto_now_add=True)),
                ('adminuser', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='kullanimAlani',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kullanimAlani', models.CharField(max_length=20)),
                ('abone_ucret', models.FloatField()),
                ('tek_girislik_ucret', models.FloatField()),
                ('kullanim_suresi', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='userInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefonNumarasi', models.CharField(max_length=15)),
                ('hesap_olusturma_tarihi', models.DateTimeField(auto_now_add=True)),
                ('kullanimTipi', models.CharField(choices=[('Abone', 'Abone'), ('Tek Giris', 'Tek Giris')], max_length=20)),
                ('bakiye', models.FloatField(default=0.0)),
                ('kartId', models.CharField(max_length=30, unique=True)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aboneApp.adminusermodel')),
                ('kullanimAlani', models.ManyToManyField(to='aboneApp.kullanimalani')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='turnikeID',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turnikeId', models.IntegerField(unique=True)),
                ('turnikeAdi', models.CharField(max_length=20)),
                ('kullanilacakAlan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aboneApp.kullanimalani')),
            ],
        ),
        migrations.CreateModel(
            name='bakiyeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yuklenenBakiye', models.FloatField()),
                ('yuklenenZaman', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bakiyelog', to='aboneApp.userinformation')),
            ],
        ),
        migrations.CreateModel(
            name='aktiviteKullanimi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('girdigiZaman', models.DateTimeField(auto_now_add=True)),
                ('ciktigiZaman', models.DateTimeField(auto_now=True)),
                ('giris_durumunda_mi', models.BooleanField(default=False)),
                ('odenen_tutar', models.FloatField(default=0)),
                ('girdigiYer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aktiviteKullanimi', to='aboneApp.kullanimalani')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aktiviteKullanimi', to='aboneApp.userinformation')),
            ],
        ),
    ]
